version: "3.7"

services:
  nginx:
    container_name: nginx
    build:
      context: ./.docker/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./logs/nginx:/var/log/nginx/
    networks:
      - symfony
  
  php-fpm:
    container_name: php-fpm
    build:
      context: ./.docker/php-fpm
      args:
        TIMEZONE: Europe/Madrid
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ./:/var/www
    networks:
      - symfony

  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "${MYSQL_EXPOSED_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
      - ./logs/mysql:${MYSQL_LOG_DIR}
    networks:
      - symfony

networks:
  symfony:
